on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: build

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: cmake
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=${HOME}/local
      - run: cmake --build build -j 2
      - run: cmake --install build
      - run: ctest -V -j 2
        working-directory: ./build
